---
docker_version: '17.06'

docker_package_info:
  pkgs:

docker_repo_key_info:
  repo_keys:

docker_repo_info:
  repos:

docker_dns_servers_strict: yes

docker_container_storage_setup: false

docker_rh_repo_base_url: 'https://download.docker.com/linux/centos/7/x86_64/stable'
docker_rh_repo_gpgkey: 'https://download.docker.com/linux/centos/gpg'
docker_apt_repo_base_url: 'https://apt.dockerproject.org/repo'
docker_apt_repo_gpgkey: 'https://apt.dockerproject.org/gpg'
